name: Deploy to AWS
on:
  push:
    branches:
      - aws-release
    tags-ignore:
      - "*beta"

jobs:
  tag:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract Plugin Version from `unusedcss.php`
        id: version
        run: |
          VERSION=$(grep -m 1 "Version:" unusedcss.php | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract Data from `readme.json`
        id: readme
        run: |
          # Extract metadata from readme.json
          TESTED_UPTO=$(jq -r '.tested_up_to' readme.json)
          REQUIRES_PHP=$(jq -r '.requires_php' readme.json) 
          STABLE_TAG=$(jq -r '.stable_tag' readme.json)
          REQUIRES_AT_LEAST=$(jq -r '.requires_at_least' readme.json)

          # Get changelog directly from changelog key
          CHANGELOG=$(jq -r '.changelog' readme.json)
          
          if [ -z "$CHANGELOG" ]; then
            echo "Warning: No changelog found"
            CHANGELOG="<h4>Version ${{ env.VERSION }}</h4><ul><li>Release</li></ul>"
          fi

          # Extract description from readme.json
          DESCRIPTION=$(jq -r '.description' readme.json)

          # Store extracted values in environment variables
          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$DESCRIPTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "TESTED_UPTO=$TESTED_UPTO" >> $GITHUB_ENV
          echo "REQUIRES_PHP=$REQUIRES_PHP" >> $GITHUB_ENV
          echo "STABLE_TAG=$STABLE_TAG" >> $GITHUB_ENV
          echo "REQUIRES_AT_LEAST=$REQUIRES_AT_LEAST" >> $GITHUB_ENV
          echo "HOMEPAGE=https://rapidload.io" >> $GITHUB_ENV

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Zip Plugin Files
        run: |
          PLUGIN_NAME="unusedcss"
          # Create zip directly without wrapping folder
          zip -r "${PLUGIN_NAME}.zip" . -x ".git/*" ".github/*" "*.zip"
          # Remove everything except the zip
          find . -mindepth 1 -maxdepth 1 ! -name "${PLUGIN_NAME}.zip" -exec rm -rf {} +

      - name: List Files
        run: |
          pwd
          ls -la

      - name: Upload Plugin ZIP to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "."
          DEST_DIR: "download/${{ env.VERSION }}"

      - name: Upload Plugin ZIP to S3 latest
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "."
          DEST_DIR: "latest"

      - name: Generate Update JSON
        run: |
          mkdir -p plugin-update-check
          cat <<EOF > plugin-update-check/update.json
          {
            "version": "${{ env.VERSION }}",
            "download_url": "https://plugin.rapidload.ai/download/${{ env.VERSION }}/unusedcss.zip",
            "requires": "5.0",
            "tested": "${{ env.TESTED_UPTO }}",
            "requires_php": "${{ env.REQUIRES_PHP }}",
            "slug": "unusedcss",
            "name": "RapidLoad AI - Optimize Web Vitals Automatically",
            "author": "RapidLoad",
            "author_homepage": "https://rapidload.ai",
            "homepage": "${{ env.HOMEPAGE }}",
            "license": "GPLv3",
            "license_uri": "https://www.gnu.org/licenses/gpl-3.0.html",
            "last_updated": "$(date +'%Y-%m-%d')",
            "sections": {
              "description": "${{ env.DESCRIPTION }}",
              "installation": "1. Upload the plugin files to the `/wp-content/plugins/unusedcss` directory, or install the plugin through WordPress.\\n2. Activate the plugin.\\n3. Configure settings under 'RapidLoad AI'.",
              "changelog": "${{ env.CHANGELOG }}",
              "faq": "<strong>Q: How much does it cost?</strong><br>A: Starts at $10/month via [RapidLoad.io](https://rapidload.io).<br><br><strong>Q: Will this work with WooCommerce?</strong><br>A: Yes, it fully supports WooCommerce."
            }
          }
          EOF

      - name: Upload Update JSON to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./plugin-update-check"
          DEST_DIR: "download/"
